# Generated by Django 4.1.3 on 2023-04-18 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Görev Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Personel Adı')),
                ('image', models.FileField(upload_to=None, verbose_name='Personel Fotoğrafı')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BESK.job', verbose_name='Peronel Görevi')),
            ],
        ),
    ]
