# Generated by Django 4.1.3 on 2023-04-18 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BESK', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Birim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Görev Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Program Adı')),
                ('image', models.FileField(upload_to=None, verbose_name='Program Fotoğrafı')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BESK.birim', verbose_name='Program Görevi')),
            ],
        ),
    ]
