# Generated by Django 4.1.3 on 2023-04-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BESK', '0005_alter_proje_finish_alter_proje_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proje',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Proje Adı'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='who',
            field=models.CharField(max_length=255, verbose_name='Proje Kimin?'),
        ),
    ]
