# Generated by Django 4.1.3 on 2023-04-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BESK', '0006_alter_proje_name_alter_proje_who'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faaliyet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Faaliyet Alanları')),
                ('subname', models.CharField(max_length=255, verbose_name='Faaliyet Konusu')),
            ],
        ),
    ]
