# Generated by Django 4.1.3 on 2023-04-19 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BESK', '0007_faaliyet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faaliyet',
            name='subname',
        ),
        migrations.CreateModel(
            name='FaaliyetKonu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Faaliyet Konusu')),
                ('faaliyet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BESK.faaliyet', verbose_name='Faaliyet Alanı')),
            ],
        ),
    ]
