# Generated by Django 4.1.3 on 2023-04-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BESK', '0008_remove_faaliyet_subname_faaliyetkonu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=None, verbose_name='Proje Görseli')),
                ('name', models.CharField(max_length=255, verbose_name='Proje Adı')),
                ('who', models.CharField(max_length=255, verbose_name='Proje Kime')),
            ],
        ),
    ]
