# Generated by Django 4.1.3 on 2023-04-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BESK', '0010_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kullanıcı Telefonu'),
        ),
    ]
