# Generated by Django 4.1.3 on 2023-04-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BESK', '0011_alter_contact_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImage',
        ),
        migrations.AddField(
            model_name='proje',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=None, verbose_name='Proje Görseli'),
        ),
    ]
