# Generated by Django 4.1.3 on 2023-04-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BESK', '0012_delete_projectimage_proje_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='proje',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to=None, verbose_name='Proje Görseli'),
        ),
        migrations.AddField(
            model_name='proje',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=None, verbose_name='Proje Görseli'),
        ),
    ]
