# Generated by Django 4.1.3 on 2023-04-20 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BESK', '0013_proje_image1_proje_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='proje',
            name='sehir',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sehir'),
        ),
        migrations.AddField(
            model_name='proje',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BESK.team', verbose_name='Proje Sorumlusu'),
        ),
        migrations.AddField(
            model_name='proje',
            name='ulke',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ülke'),
        ),
    ]
